### PR TITLE
docs: Add panacea-3 upgrade guide

### PR DESCRIPTION
**Pull request by youngjoon-lee**
TODO: to be refined as soon as the new Panacea version is released.

### CODE REVIEW

**Review by gyuguen — APPROVED** [review]
👍 
It's a detailed guide.

**Comment by youngjoon-lee** [comment]
@gyuguen 
I just modified documents to suggest to use v2.0.0-alpha.1 temporarily. Please review this one more time.
3d52488

**Review by gyuguen — APPROVED** [review]
👍 
Thank you for your efforts

**Comment by youngjoon-lee** [comment]
> Oh, the last release tag is `v1.3.3-internal`

Yeah. That part is tricky. Other full node operators are using v1.3.3. But, MediBloc uses v1.3.3-internal for operating validator nodes. v1.3.3-internal uses [a forked cosmos-sdk](https://github.com/medibloc/panacea-core/blob/cbce38a79f740b9bf5d56571417b4206e5218d63/go.mod#L29) that is hard-coded to disable the `create-validator` transaction.
https://github.com/medibloc/cosmos-sdk/commit/727746c89b9907528e936fad587600945c6f8a90

From v2.0.0, we don't need any `*-internal` tag anymore.

**Comment by gyuguen** [comment]
> > Oh, the last release tag is `v1.3.3-internal`
> 
> Yeah. That part is tricky. Other full node operators are using v1.3.3. But, MediBloc uses v1.3.3-internal for operating validator nodes. v1.3.3-internal uses [a forked cosmos-sdk](https://github.com/medibloc/panacea-core/blob/cbce38a79f740b9bf5d56571417b4206e5218d63/go.mod#L29) that is hard-coded to disable the `create-validator` transaction.
> 
> From v2.0.0, we don't need any `*-internal` tag anymore.

OK!

**Pull request merged**
